# Generated by Django 3.2.5 on 2021-08-08 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('AU', 'Austailia'), ('LAX', 'Los Angeles'), ('SFO', 'San Francisco')], default='Los Angeles', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['office', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_type', models.CharField(blank=True, choices=[('ACCOUNTING', 'Accounting'), ('COMPLIANCE', 'Compliance/Processing'), ('MANAGEMENT', 'Management'), ('OPERATIONS', 'Operations'), ('PETCARE', 'Petcare'), ('SALES', 'Sales'), ('SECURITY', '  TSA Security'), ('SITEADMIN', 'Site Admin')], default='Petcare', max_length=100)),
                ('description', models.CharField(blank=True, max_length=125, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_type', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ACCOUNTANT', 'Accountant'), ('ASSISTANT_MANAGER', 'Assistant Manager'), ('CONTRACTOR', 'Contractor'), ('COMPLIANCE', 'Compliance/Processing'), ('DEV', 'Developer'), ('DRIVER', 'Driver, Pet Handler'), ('GUEST', 'GUEST'), ('MANAGER', 'Manager'), ('OPERATIONS_LEAD', 'Operations Lead'), ('OPERATIONS_ASSISTANT', 'Operations Assistant'), ('OWNER', 'Owner'), ('SALESPERSON', 'Salesperson'), ('SECURITY_COORDINATOR', 'Security Coordinator'), ('VET', 'Vet'), ('WEBSITE_ADMIN', 'Website Admin')], default='Contractor', max_length=200)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['title', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='media/default.png', upload_to=employees.models.upload_to, verbose_name='Avatar')),
                ('drivers_license', models.CharField(blank=True, max_length=20, verbose_name='Drivers License')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('emergency_contact', models.CharField(max_length=200, verbose_name='Emergency Contact Name')),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, verbose_name='Emergency Conatct Number')),
                ('birth_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Birth Date')),
                ('hire_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Hire Date')),
                ('employeetype', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract'), ('TRAINEE', 'Trainee')], max_length=15, null=True, verbose_name='Employee Type')),
                ('sta_number', models.CharField(max_length=200, verbose_name='STA Number')),
                ('manager', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False, help_text='button to toggle employee deleted and undelete', verbose_name='Is Deleted')),
                ('is_manager', models.BooleanField(default='False')),
                ('team_lead', models.CharField(max_length=200)),
                ('is_team_lead', models.BooleanField(default='False')),
                ('supervisor', models.CharField(max_length=200)),
                ('supervisor_status', models.BooleanField(default='False')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('department_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-hire_date'],
            },
        ),
    ]
