# Generated by Django 3.2.5 on 2021-08-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_employee_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(blank=True, choices=[('ACCOUNTING', 'Accounting'), ('COMPLIANCE', 'Compliance/Processing'), ('CONTRACTOR', 'Contractor'), ('HUMAN RESOURCES', 'Human Resources'), ('MANAGEMENT', 'Management'), ('OPERATIONS', 'Operations'), ('PETCARE', 'Petcare'), ('SALES', 'Sales'), ('SECURITY', '  TSA Security'), ('SITEADMIN', 'Site Admin'), ('VET', 'Vet')], default='Petcare', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='About'),
        ),
    ]
