# Generated by Django 3.2.5 on 2021-08-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210814_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='about',
        ),
    ]
