# Generated by Django 3.2.5 on 2021-08-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210814_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_type',
            field=models.CharField(blank=True, choices=[('ACCOUNTING', 'Accounting'), ('COMPLIANCE', 'Compliance/Processing'), ('CONTRACTOR', 'Contractor'), ('HUMAN RESOURCES', 'Human Resources'), ('MANAGEMENT', 'Management'), ('OPERATIONS', 'Operations'), ('PETCARE', 'Petcare'), ('SALES', 'Sales'), ('SECURITY', '  TSA Security'), ('SITEADMIN', 'Site Admin'), ('VET', 'Vet')], default='Petcare', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(choices=[('AU', 'Austailia'), ('LAX', 'Los Angeles'), ('SFO', 'San Francisco')], default='Los Angeles', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_title',
            field=models.CharField(choices=[('ACCOUNTANT', 'Accountant'), ('ASSISTANT_MANAGER', 'Assistant Manager'), ('CONTRACTOR', 'Contractor'), ('COMPLIANCE', 'Compliance/Processing'), ('DEV', 'Developer'), ('DRIVER', 'Driver, Pet Handler'), ('GUEST', 'GUEST'), ('MANAGER', 'Manager'), ('OPERATIONS_LEAD', 'Operations Lead'), ('OPERATIONS_ASSISTANT', 'Operations Assistant'), ('OWNER', 'Owner'), ('SALES_LEAD', 'Sales Lead'), ('SALES_PERSON', 'Sales Person'), ('SECURITY_COORDINATOR', 'Security Coordinator'), ('VET', 'Vet'), ('WEBSITE_ADMIN', 'Website Admin')], default='Contractor', max_length=200),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
