# Generated by Django 3.2.5 on 2021-08-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20210815_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(max_length=15, null=True, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
