# Generated by Django 3.2.5 on 2021-08-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sta_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='STA Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team_lead',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
