# Generated by Django 3.2.5 on 2021-08-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20210815_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hiring_docs',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='sta_docs',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
