# Generated by Django 3.2.5 on 2021-08-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20210815_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sta_exp',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
