# Generated by Django 3.2.5 on 2021-09-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_auto_20210907_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='followers',
        ),
    ]
