# Generated by Django 3.2.5 on 2021-08-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name')),
                ('quantity', models.IntegerField(blank=True, default='0', null=True, verbose_name='Quantity')),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('recieve_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('category', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
