# Generated by Django 3.2.5 on 2021-08-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_time_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='recieve_by',
            new_name='receive_by',
        ),
    ]
