# Generated by Django 3.2.5 on 2021-08-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_recieve_by_inventory_receive_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='issue_by',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='issue_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='issue_to',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='receive_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reorder_level',
        ),
    ]
