# Generated by Django 3.2.5 on 2021-09-28 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scooby', models.CharField(blank=True, max_length=50, null=True, verbose_name='Scooby')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('pets', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pets')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address2')),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zipcode')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact')),
                ('primary_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Contact')),
                ('contact_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'INactive')], default='ACTIVE', max_length=100, null=True, verbose_name='Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
