# Generated by Django 3.2.5 on 2021-09-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'INactive')], max_length=100, null=True, verbose_name='Category'),
        ),
    ]
