# Generated by Django 3.2.5 on 2021-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='category',
        ),
        migrations.AddField(
            model_name='client',
            name='active_client',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'INactive')], max_length=100, null=True, verbose_name='Active'),
        ),
    ]
