# Generated by Django 3.2.5 on 2021-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active_client',
            field=models.CharField(blank=True, choices=[('IS ACTIVE', 'Active'), ('NOT ACTIVE', 'Inactive')], max_length=100, null=True, verbose_name='Active'),
        ),
    ]
