# Generated by Django 3.2.5 on 2021-10-14 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_auto_20210807_2248'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_alter_client_active_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('urine', models.BooleanField(default=False)),
                ('fecal', models.BooleanField(default=False)),
                ('rx_given', models.BooleanField(default=False)),
                ('rx_type', models.CharField(blank=True, max_length=100, null=True)),
                ('play_time', models.CharField(blank=True, max_length=100, null=True)),
                ('food_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('treat_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('client_emailed', models.BooleanField(default=False)),
                ('client_called', models.BooleanField(default=False)),
                ('photo_taken', models.BooleanField(default=False)),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='pets',
        ),
        migrations.AddField(
            model_name='client',
            name='airline',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airlines.airline'),
        ),
        migrations.AddField(
            model_name='client',
            name='awb1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='awb2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='awb3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='awb4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dom_airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dom_cutoff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dom_flight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='int_airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='int_cutoff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='int_flight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('temperment', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medication', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, max_length=100, null=True)),
                ('food_type', models.CharField(blank=True, max_length=100, null=True)),
                ('food_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('food_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('feed_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('treat_allowed', models.BooleanField(default=False)),
                ('treat_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('treat_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('crate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('crate_size', models.CharField(blank=True, max_length=100, null=True)),
                ('microchip', models.CharField(blank=True, max_length=100, null=True)),
                ('escape_artist', models.BooleanField(default=False)),
                ('eyes_in', models.CharField(blank=True, max_length=100, null=True)),
                ('eyes_out', models.CharField(blank=True, max_length=100, null=True)),
                ('paws_in', models.CharField(blank=True, max_length=100, null=True)),
                ('paws_out', models.CharField(blank=True, max_length=100, null=True)),
                ('mouth_in', models.CharField(blank=True, max_length=100, null=True)),
                ('mouth_out', models.CharField(blank=True, max_length=100, null=True)),
                ('nose_in', models.CharField(blank=True, max_length=100, null=True)),
                ('nose_out', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('moa_date', models.CharField(blank=True, max_length=100, null=True)),
                ('fwd_date', models.CharField(blank=True, max_length=100, null=True)),
                ('fw_time', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=100, null=True)),
                ('transport_type', models.CharField(blank=True, max_length=100, null=True)),
                ('last_meal', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name5', models.CharField(blank=True, max_length=100, null=True)),
                ('pet_photo', models.CharField(blank=True, max_length=100, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.activity')),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='pet',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.pet', verbose_name='Pets'),
        ),
    ]
