# Generated by Django 3.2.5 on 2021-10-14 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0009_auto_20211013_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='medication',
        ),
        migrations.AddField(
            model_name='pet',
            name='medication1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication1'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication1'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication3'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication4'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_dose1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication Dose 1'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_dose2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication Dose 2'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_dose3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication Dose 3'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_dose4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication Dose 4'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_freq1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication Frequency 1'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_freq2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication Frequency 2'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_freq3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication Frequency 3'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medication_freq4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medication Frequency 4'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('PLAY TIME', 'Play Time'), ('OPEN PLAY', 'Open Play'), ('VET VISIT', 'Vet Visit'), ('WALK', 'Walk'), ('CLEANED ROOM', 'Cleaned Room'), ('WATERED', 'Watered'), ('BATHED', 'Bathed'), ('GIVEN MEDICATION', 'Given Medication'), ('FED', 'Fed'), ('TREAT', 'Treat'), ('PHOTO TAKEN', 'Photo Taken'), ('CLIENT UPDATED', 'Client Updated'), ('PENDING', 'Pending')], default='Pending', max_length=100, null=True, verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='client_called',
            field=models.BooleanField(default=False, verbose_name='Client Called'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='client_emailed',
            field=models.BooleanField(default=False, verbose_name='Client Emailed'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='fecal',
            field=models.BooleanField(default=False, verbose_name='Fecal'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='food_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Food Amount'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Handler'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photo_taken',
            field=models.BooleanField(default=False, verbose_name='Photo Taken'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='play_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Play Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rx_given',
            field=models.BooleanField(default=False, verbose_name='RX Given'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rx_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RX Type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='treat_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Treat Amount'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='urine',
            field=models.BooleanField(default=False, verbose_name='Urine'),
        ),
        migrations.AlterField(
            model_name='client',
            name='awb1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AWB 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='awb2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AWB 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='awb3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AWB 3'),
        ),
        migrations.AlterField(
            model_name='client',
            name='awb4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AWB 4'),
        ),
        migrations.AlterField(
            model_name='client',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dom_airline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doemestic Airline'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dom_cutoff',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domestic CutOff'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dom_flight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domestic Flight'),
        ),
        migrations.AlterField(
            model_name='client',
            name='int_airline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='International Airline'),
        ),
        migrations.AlterField(
            model_name='client',
            name='int_cutoff',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='International Cutoff'),
        ),
        migrations.AlterField(
            model_name='client',
            name='int_flight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='International Flight'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Checked In By'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='crate_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Crate Size'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='crate_type',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('OWN', 'Own')], default='BUY', max_length=100, null=True, verbose_name='Crate Type'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='delivery_date',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Location'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='escape_artist',
            field=models.BooleanField(default=False, verbose_name='Escape Artist'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='eyes_in',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Eyes At Check In'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='eyes_out',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Eyes At Check Out'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='feed_frequency',
            field=models.CharField(blank=True, choices=[('1 X DAILY', '1 X Daily'), ('2 X DAILY', '2 X Daily'), ('3 X DAILY', '3 X Daily'), ('4 X DAILY', '4 X Daily')], default='2 X DAILY', max_length=100, null=True, verbose_name='Feed Frequency'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='food_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Food Amount'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='food_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Food Brand'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='food_type',
            field=models.CharField(blank=True, choices=[('PET EXPRESS FOOD', 'Pet Express Food'), ('OWN FOOD', 'Own Food')], default='PET EXPRESS FOOD', max_length=100, null=True, verbose_name='Food Type'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='fw_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forward Time'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='fwd_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forward Date'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item 1'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='item_name2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item 2'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='item_name3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item 3'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='item_name4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item 4'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='item_name5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item 5'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_meal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Meal'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='microchip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Microchip'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='moa_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MOA Date'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='mouth_in',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Mouth At Check In'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='mouth_out',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Mouth At Check Out'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nose_in',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Nose At Check In'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nose_out',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Nose At Check Out'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='paws_in',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Paws at Check In'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='paws_out',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('Issue', 'Issue')], default='GOOD', max_length=100, null=True, verbose_name='Paws at Check Out'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pet Name'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pet Photo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='temperment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Temperment'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('MEET AT OFFICE', 'Meet At Office'), ('CUT OFF', 'Cut Off')], default='DELIVERY', max_length=100, null=True, verbose_name='Transport Type'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='treat_allowed',
            field=models.BooleanField(default=False, verbose_name='Treat allowed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='treat_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Treat Amount'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='treat_frequency',
            field=models.CharField(blank=True, choices=[('1 X DAILY', '1 X Daily'), ('2 X DAILY', '2 X Daily'), ('3 X DAILY', '3 X Daily'), ('4 X DAILY', '4 X Daily')], default='2 X DAILY', max_length=100, null=True, verbose_name='Treat Freqeuncy'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weight'),
        ),
    ]
