# Generated by Django 3.2.5 on 2021-08-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, choices=[('AIR ANIMAL-IAC:OWN TESTING/STA', 'Air Animal-IAC: Own Testing/STA'), ('AIRBORNE ANIMALS', 'Airborne Animals'), ('AIRPETS AMERICA', 'Airpets America'), ('AIRVETS PET RELOCATION', 'AirVets Pet Relocation'), ('AMERICAN EXPEDITING', 'American Expediting'), ('ANIMAL MOTEL', 'Animal Motel'), ('THE ARK JFK', 'The Ark JFK'), ('ARTWOOD PET TRANSPORT', 'Artwood Pet Transport'), ('BARKING BARBERS', 'Barking Barbers'), ("BOBBIE'S PET WORLD:OWN TRAINING", "Bobbie's Pet World:Own Training"), ("BRIT'S BOW WOW", "Brit's Bow Wow"), ('CAPITOL PET MOVERS', 'Capitol Pet Movers'), ('CHICAGO PET TRAVEL', 'Chicago Pet Travel'), ('CLUB PET INTERNATIONAL', 'Club Pet Intertional'), ('COME SIT STAY PET RESORT', 'Come Sit Stay Pet Resort'), ('CONTINENTAL PET RELOCATION(CHAROLETTE)', 'Continental Pet Relocation(Charolette)'), ('COUNTRY LANE PET RESORT', 'Country Lane Pet Resort'), ('DOG GONE TAXI- SEA', 'Dog Gone Taxi- SEA'), ("THE DIPPIN' DOG:NEED TRAINING", "The Dippin' Dog:Need Training "), ('DSC PETS 2 GO LLC', 'DSC Pet 2 Go LLC'), ('GOLDWOOD KENNELS', 'Goldwood Kennels'), ("HORKY'S PAWS", "Horky's Paws"), ('KRISDAN KENNEL', 'Krisdan Kennel'), ('LYNN BUREK', 'Lyn Burek'), ('MERIDA ENTERPRISE', 'MERIDA ENTERPRISE'), ("MIKE'S COAST TO COAST PET TRANSIT LLC", "Mike's Coast To Coast Pet Transit LLC"), ('PACK YOUR PETS', 'Pack Your Pets'), ('PAWS AROUND CHICAGO', 'Paws Around Chicago'), ('PET AIR', 'Pet Air'), ('PET AWAY', 'Pet Away'), ('PET RELOCATOR', 'Pet Relocator'), ('PETSFLY DENVER', 'Petsfly Denver'), ('PETSFLY VEGAS', 'Petsfly Vegas'), ('PETSFLY ORD', 'Petsfly ORD'), ('PETSFLY PHX', 'Petsfly PHX'), ('PETS ON THE GO "HOURGLASS INC DBA"', 'Pets On The Go "Hourglass Inc DBA'), ('PETS 2 VETS', 'Pets 2 Vets'), ('PETS WITH PASSPORTS', 'Pets With Passports'), ('PUPPY TRAVEL.COM: IAC', 'Puppy Travel.com: IAC'), ('RABBIT CREEK KENNEL', 'Rabbit Creek Kennel'), ('ROB CARY PET RESORT', 'ROB CARY PET RESORT'), ('SHIP MY PETS', 'Ship My Pets'), ('SLEEPY HOLLOW PET RANCH', 'Sleepy Hollow Pet Ranch'), ('STARWOOD ANIMAL TRANSPORT(GLOBAL PET)', 'Starwood Animnal Transport(Global Pet)'), ('TOWN AND COUNTRY PET CARE CENTER', 'Town and Country Pet Care Center'), ('THE TRANSPETTERS', 'The Transpetters'), ('THE WAGGIN TRAVEL EXPRESS', 'The Waggin Travel Express'), ('WORLD PET TRAVEL', 'World Pet Travel')], max_length=200)),
                ('main_contact', models.CharField(blank=True, max_length=50)),
                ('agent_employee', models.CharField(blank=True, max_length=50)),
                ('email_contact', models.CharField(blank=True, max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('sta_agent_number', models.CharField(blank=True, max_length=50)),
                ('sta_agent_exp', models.DateField()),
                ('notes', models.TextField(blank=True, max_length=200)),
                ('tsa_training_exp1', models.CharField(blank=True, max_length=50)),
                ('tsa_training_exp2', models.CharField(blank=True, max_length=50)),
                ('tsa_training_form1', models.FileField(null=True, upload_to='')),
                ('tsa_training_form2', models.FileField(null=True, upload_to='')),
                ('tsa_form', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
