# Generated by Django 3.2.5 on 2021-09-24 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, null=True, verbose_name='Inovice Number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Name')),
                ('scooby', models.CharField(blank=True, max_length=50, null=True, verbose_name='Scooby')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('pet_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pet Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zipcode')),
                ('state_or_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='State or Province')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('category_1', models.CharField(choices=[('CRATE PICK UP', 'Crate Pick Up'), ('CRATE DELIVERY', 'Pet Delivery'), ('PET AIRFARE', 'Pet Airfare'), ('PET COMFORT STOP', 'Pet Comfort Stop'), ('PET DELIVERY', 'Pet Delivery'), ('PET BATH/GROOMING', 'Pet Bath/Grooming'), ('PET Emergency SERVICE', 'Pet Emergency Service'), ('PET VETERINARY SERVICE', 'Pet Veterinary Service'), ('PET BOARDING', 'Pet Boarding'), ('PET PICK UP', 'Pet Pick Up'), ('OTHER', 'Other')], default='PET BOARDING', max_length=100, verbose_name='Category 1')),
                ('name_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name 1')),
                ('price_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price 1')),
                ('quantity_1', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity 1')),
                ('total_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total 1')),
                ('category_2', models.CharField(choices=[('CRATE PICK UP', 'Crate Pick Up'), ('CRATE DELIVERY', 'Pet Delivery'), ('PET AIRFARE', 'Pet Airfare'), ('PET COMFORT STOP', 'Pet Comfort Stop'), ('PET DELIVERY', 'Pet Delivery'), ('PET BATH/GROOMING', 'Pet Bath/Grooming'), ('PET Emergency SERVICE', 'Pet Emergency Service'), ('PET VETERINARY SERVICE', 'Pet Veterinary Service'), ('PET BOARDING', 'Pet Boarding'), ('PET PICK UP', 'Pet Pick Up'), ('OTHER', 'Other')], default='PET BOARDING', max_length=100, verbose_name='Category 2')),
                ('name_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name 2')),
                ('price_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price 2')),
                ('quantity_2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity 2')),
                ('total_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total 2')),
                ('category_3', models.CharField(choices=[('CRATE PICK UP', 'Crate Pick Up'), ('CRATE DELIVERY', 'Pet Delivery'), ('PET AIRFARE', 'Pet Airfare'), ('PET COMFORT STOP', 'Pet Comfort Stop'), ('PET DELIVERY', 'Pet Delivery'), ('PET BATH/GROOMING', 'Pet Bath/Grooming'), ('PET Emergency SERVICE', 'Pet Emergency Service'), ('PET VETERINARY SERVICE', 'Pet Veterinary Service'), ('PET BOARDING', 'Pet Boarding'), ('PET PICK UP', 'Pet Pick Up'), ('OTHER', 'Other')], default='PET BOARDING', max_length=100, verbose_name='Category 3')),
                ('name_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name 3')),
                ('price_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price 3')),
                ('quantity_3', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity 3')),
                ('total_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total 3')),
                ('category_4', models.CharField(choices=[('CRATE PICK UP', 'Crate Pick Up'), ('CRATE DELIVERY', 'Pet Delivery'), ('PET AIRFARE', 'Pet Airfare'), ('PET COMFORT STOP', 'Pet Comfort Stop'), ('PET DELIVERY', 'Pet Delivery'), ('PET BATH/GROOMING', 'Pet Bath/Grooming'), ('PET Emergency SERVICE', 'Pet Emergency Service'), ('PET VETERINARY SERVICE', 'Pet Veterinary Service'), ('PET BOARDING', 'Pet Boarding'), ('PET PICK UP', 'Pet Pick Up'), ('OTHER', 'Other')], default='PET BOARDING', max_length=100, verbose_name='Category 4')),
                ('name_4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name 4')),
                ('price_4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price 4')),
                ('quantity_4', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity 4')),
                ('total_4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total 4')),
                ('category_5', models.CharField(choices=[('CRATE PICK UP', 'Crate Pick Up'), ('CRATE DELIVERY', 'Pet Delivery'), ('PET AIRFARE', 'Pet Airfare'), ('PET COMFORT STOP', 'Pet Comfort Stop'), ('PET DELIVERY', 'Pet Delivery'), ('PET BATH/GROOMING', 'Pet Bath/Grooming'), ('PET Emergency SERVICE', 'Pet Emergency Service'), ('PET VETERINARY SERVICE', 'Pet Veterinary Service'), ('PET BOARDING', 'Pet Boarding'), ('PET PICK UP', 'Pet Pick Up'), ('OTHER', 'Other')], default='PET BOARDING', max_length=100, verbose_name='Category 5')),
                ('name_5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name 5')),
                ('price_5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price 5')),
                ('quantity_5', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity 5')),
                ('total_5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total 5')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('balance', models.CharField(blank=True, max_length=50, null=True, verbose_name='Balance')),
                ('total', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total')),
                ('timestamp', models.DateTimeField()),
                ('paid', models.BooleanField(default=False, verbose_name='Total 4')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Paid')),
                ('invoice_type', models.CharField(blank=True, choices=[('RECIEPT', 'Receipt'), ('PROFORMA INVOICE', 'Proforma Invoice'), ('INVOICE', 'Invoice')], default='INVOICE', max_length=50, null=True, verbose_name='Invoice Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
