# Generated by Django 3.2.5 on 2021-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_1',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Price 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_2',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Price 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_3',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Price 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_4',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Price 4'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_5',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Price 5'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_1',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Total 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_2',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Total 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_3',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Total 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_4',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Total 4'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_5',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='Total 5'),
        ),
    ]
