# Generated by Django 3.2.5 on 2021-09-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210924_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='country',
        ),
    ]
