# Generated by Django 3.2.5 on 2021-09-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210926_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='scooby',
        ),
    ]
