# Generated by Django 3.2.5 on 2021-09-30 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_active_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0005_auto_20210928_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='category',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.IntegerField(blank=True, default=14, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Gross Amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('RECIEPT', 'Receipt'), ('PROFORMA INVOICE', 'Proforma Invoice'), ('INVOICE', 'Invoice'), ('CREDIT', 'Credit')], default='INVOICE', max_length=50, null=True, verbose_name='Invoice Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_credit_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice', verbose_name='Credit For'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Is Sent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Net Amount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sender Reference'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Vat/Tax Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('PURCHASE CRATE', 'Purchase Crate'), ('SHIP CRATE', 'Ship Crate'), ('CRATE PICK UP', 'Crate Pick Up'), ('CRATE DELIVERY', 'Pet Delivery'), ('PET AIRFARE', 'Pet Airfare'), ('PET COMFORT STOP', 'Pet Comfort Stop'), ('PET DELIVERY', 'Pet Delivery'), ('PET BATH/GROOMING', 'Pet Bath/Grooming'), ('PET Emergency SERVICE', 'Pet Emergency Service'), ('PET VETERINARY SERVICE', 'Pet Veterinary Service'), ('PET BOARDING', 'Pet Boarding'), ('PET PICK UP', 'Pet Pick Up'), ('OTHER', 'Other')], default='PURCHASE CRATE', max_length=255, verbose_name='Service')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Unit Price')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Net Amount')),
                ('vat_rate', models.IntegerField(default=0, verbose_name='Vat/Tax Rate')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice', verbose_name='Invoice')),
            ],
        ),
    ]
