# Generated by Django 3.2.5 on 2021-09-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_active_client'),
        ('invoice', '0006_auto_20210930_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client', verbose_name='Client'),
        ),
    ]
