# Generated by Django 2.2.1 on 2021-07-20 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office', models.CharField(choices=[('AU', 'Austailia'), ('LAX', 'Los Angeles'), ('SFO', 'San Francisco')], default='Los Angeles', max_length=200)),
                ('deparment', models.TextField(blank=True, choices=[('ACCOUNTANTING', 'Accountanting'), ('COMPLIANCE', 'Compliance/Processing'), ('MANAGEMENT', 'Management'), ('OPERATIONS', 'Operations'), ('PETCARE', 'Petcare'), ('SALES', 'Sales'), ('SECURITY', '  TSA Security')], default='Petcare')),
                ('title', models.CharField(choices=[('ACCOUNTANT', 'Accountant'), ('ASSISTANT_MANAGER', 'Assistant Manager'), ('CONTRACTOR', 'Contractor'), ('COMPLIANCE', 'Compliance/Processing'), ('COMPLIANCE_LEAD', 'Compliance/Processing Lead'), ('COMPLIANCE_TRAINEE', 'Compliance/Processing Trainee'), ('DEV', 'Devloper'), ('DRIVER', 'Driver'), ('DRIVER_LEAD', 'Driver Lead'), ('DRIVER_TRAINEE', 'Driver Trainee'), ('GUEST', 'GUEST'), ('MANAGER', 'Manager'), ('OPERATIONS_LEAD', 'Operations Lead'), ('OPERARATIONS_ASSITANT', 'Operations Assitant'), ('OWNER', 'Owner'), ('PETHANDLER', 'Pet Handler'), ('SALESPERSON', 'Salesperson'), ('SALESPERSON_LEAD', 'Salesperson Lead'), ('SALESPERSON_TRAINEE', 'Salesperson Trainee'), ('SECURITY_COORDINATOR', 'Security Coordinator'), ('TRAINEE', 'Trainee'), ('VET', 'Vet'), ('WEBSITE_ADMIN', 'Website Admin')], default='Trainee', max_length=200)),
                ('drivers_license', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('hire_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('birth_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('sta_number', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('is_manager', models.BooleanField(default=False)),
                ('team_lead', models.CharField(max_length=200)),
                ('is_team_lead', models.BooleanField(default=False)),
                ('supervisor', models.CharField(max_length=200)),
                ('supervisor_status', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
