# Generated by Django 2.2.1 on 2021-07-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='deparment',
            new_name='department',
        ),
    ]
