# Generated by Django 3.2.5 on 2021-07-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210721_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='emergency_number',
            new_name='emergency_contact_number',
        ),
    ]
