# Generated by Django 3.2.5 on 2021-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210721_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_manager',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_team_lead',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='supervisor_status',
            field=models.BooleanField(default='False'),
        ),
    ]
