# Generated by Django 3.2.5 on 2021-07-27 01:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210721_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='banner',
            field=models.ImageField(default='media/default.png', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='picture',
            field=models.ImageField(default='media/default.png', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
