# Generated by Django 3.2.5 on 2021-08-01 21:41

import airlines.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('airline_code', models.CharField(blank=True, max_length=10)),
                ('airline_network', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('pets_flight_options', models.CharField(choices=[('BAGGAGE', 'Baggage'), ('CABIN', 'Cabin'), ('CARGO', 'Cargo'), ('OPEN', 'Open')], default='Cargo', max_length=100)),
                ('city', models.CharField(choices=[('LAX', 'Los Angeles'), ('SFO', 'San Francisco'), ('OTHER', 'Other')], default='LAX', max_length=100)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='California', max_length=100)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('cargo_phone', models.IntegerField(blank=True, null=True)),
                ('reservation_phone', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('has_grass', models.BooleanField(default=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('import_station', models.TextField(blank=True, choices=[('LEFT', 'Left hand side'), ('RIGHT', 'Right hand side'), ('SAME', 'Same building')], default='Same buidling')),
                ('export_station', models.TextField(blank=True, choices=[('LEFT', 'Left hand side'), ('RIGHT', 'Right hand side'), ('SAME', 'Same building')], default='Same buidling')),
                ('frequently_used', models.TextField(choices=[('FREQUENTLY_VISITED', 'Frequently visited'), ('RARELY_VISITED', 'Rarely visited')], default='Frequently visited')),
                ('onsite_parking', models.BooleanField(default=True)),
                ('have_account', models.BooleanField(default=True)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('acclimation_needed', models.BooleanField(default=True)),
                ('food_needed', models.BooleanField(default=True)),
                ('photo_of_pet_needed', models.BooleanField(default=True)),
                ('contact_label_needed', models.BooleanField(default=True)),
                ('cut_off_deadline', models.TextField(blank=True)),
                ('pick_up_delay', models.TextField(blank=True)),
                ('has_loading_ramp', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('crate_inspection_required', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image')),
                ('photo_1', models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image')),
                ('photo_2', models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image')),
                ('photo_3', models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image')),
                ('photo_4', models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image')),
                ('photo_5', models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image')),
                ('photo_6', models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image')),
                ('compliance_notes', models.TextField(blank=True)),
                ('driver_notes', models.TextField(blank=True)),
                ('ok_to_forward_required', models.BooleanField(default=True)),
                ('earliest_book_date', models.CharField(blank=True, max_length=100)),
                ('breed_restrictions', models.TextField(blank=True)),
                ('weather_restrictions', models.BooleanField(default=True)),
                ('pet_reservations_info', models.TextField(blank=True)),
                ('pets_checkin_options', models.CharField(choices=[('CARGO', 'Cargo'), ('AIRPORT', 'Airport'), ('TBD', 'TBD')], default='Cargo', max_length=100)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated at')),
                ('terminal_number', models.CharField(blank=True, max_length=50)),
                ('airline_docs', models.FileField(blank=True, null=True, upload_to=airlines.models.upload_to)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='airlines.category')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
