# Generated by Django 3.2.5 on 2021-07-21 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_auto_20210721_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='id',
        ),
        migrations.AddField(
            model_name='airline',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
