# Generated by Django 3.2.5 on 2021-07-22 20:22

import airlines.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0004_auto_20210721_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='pet_reservations',
            new_name='pet_reservations_info',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='Weather_restrictions',
            new_name='weather_restrictions',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='employee',
        ),
        migrations.AddField(
            model_name='airline',
            name='airline_docs',
            field=models.FileField(null=True, upload_to=airlines.models.upload_to),
        ),
        migrations.AddField(
            model_name='airline',
            name='pets_flight_options',
            field=models.CharField(choices=[('BAGGAGE', 'Baggage'), ('CABIN', 'Cabin'), ('CARGO', 'Cargo'), ('OPEN', 'OPEN')], default='Cargo', max_length=100),
        ),
        migrations.AddField(
            model_name='airline',
            name='pick_up_delay',
            field=models.TextField(blank=True, choices=[('LEFT', 'Left hand side'), ('RIGHT', 'Right hand side'), ('SAME', 'Same building')], default='Same buidling'),
        ),
        migrations.AddField(
            model_name='airline',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='airline',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='airline',
            name='cargo_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='airline',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='photo_1',
            field=models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='photo_2',
            field=models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='photo_3',
            field=models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='photo_4',
            field=models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='photo_5',
            field=models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='photo_6',
            field=models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='photo_main',
            field=models.ImageField(default='media/default.png', upload_to=airlines.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='reservation_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='airline',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='California', max_length=100),
        ),
        migrations.AlterField(
            model_name='airline',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='airline',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='airline',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='airlines.category'),
        ),
    ]
