# Generated by Django 3.2.5 on 2021-07-27 01:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0005_auto_20210722_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
