# Generated by Django 3.2.5 on 2021-07-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0006_airline_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='terminal_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='airline',
            name='pets_checkin_options',
            field=models.CharField(choices=[('CARGO', 'Cargo'), ('AIRPORT', 'Airport'), ('TBD', 'TBD')], default='Cargo', max_length=100),
        ),
        migrations.AlterField(
            model_name='airline',
            name='pets_flight_options',
            field=models.CharField(choices=[('BAGGAGE', 'Baggage'), ('CABIN', 'Cabin'), ('CARGO', 'Cargo'), ('OPEN', 'Open')], default='Cargo', max_length=100),
        ),
    ]
