# Generated by Django 3.2.5 on 2021-07-27 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airlines', '0007_auto_20210726_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='airline',
            name='employee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airline',
            name='slug',
            field=models.CharField(max_length=200, unique_for_date='published'),
        ),
    ]
