# Generated by Django 3.2.5 on 2021-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0008_auto_20210726_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
