# Generated by Django 3.2.5 on 2021-07-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0010_auto_20210729_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='is_published',
            new_name='published',
        ),
    ]
