# Generated by Django 3.2.5 on 2021-07-29 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0011_rename_is_published_airline_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='last_updated',
        ),
    ]
