# Generated by Django 3.2.5 on 2021-07-29 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0012_remove_airline_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
