# Generated by Django 3.2.5 on 2021-07-29 22:46

import airlines.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0013_auto_20210729_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airline',
            name='airline_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='airline',
            name='airline_docs',
            field=models.FileField(blank=True, null=True, upload_to=airlines.models.upload_to),
        ),
        migrations.AlterField(
            model_name='airline',
            name='cargo_phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='airlines.category'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='earliest_book_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='airline',
            name='reservation_phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airline',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
