# Generated by Django 3.2.5 on 2021-07-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0014_auto_20210729_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='have_account',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
