# Generated by Django 3.2.5 on 2021-07-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0015_alter_airline_have_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='have_account',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
