# Generated by Django 3.2.5 on 2021-07-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0016_alter_airline_have_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='have_account',
            field=models.BooleanField(default=True),
        ),
    ]
