# Generated by Django 3.2.5 on 2021-07-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0017_auto_20210729_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
