# Generated by Django 3.2.5 on 2021-07-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0018_alter_airline_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='cargo_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='reservation_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
