# Generated by Django 3.2.5 on 2021-07-29 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0019_auto_20210729_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='airlines.category'),
        ),
    ]
