# Generated by Django 3.2.5 on 2021-08-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0020_alter_airline_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
